name: Main CI

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Publish
        run: dotnet publish -c Release --no-build

      - name: Login Container Repository
        uses: docker/login-action@v1
        with:
          username: xieyubo
          password: ${{ secrets.XYB_DOCKERHUB_PASSWORD }}

      - name: Build And Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: src/
          file: src/Dockerfile
          tags: xieyubo/ipdns:${{ github.sha }}
          push: true

      - uses: azure/k8s-set-context@v1
        with:
          kubeconfig: '${{ secrets.XYB_KUBECONFIG }}'

      - name: Deploy
        uses: azure/k8s-deploy@v1
        with:
          namespace: ipdns
          manifests: |
            deployments/ipdns.yaml
          images: |
            xieyubo/ipdns:${{ github.sha }}
